### ISSUE TITLE
Add ability to clone Zstd[De]compressor

### ISSUE THREAD

**Issue by Hello1024** [animalize/pyzstd#13]
The underlying ZStd API has a `ZSTD_copyCCtx` function.  It would be good to expose this in the python API.

This allows usecases like the following:

I send a stream of compressed data, all using the same compressor for efficiency benefits.   I am thinking of sending some data, so I try to compress it, but it turns out (after compression) to be too large to send, so I decide to discard it instead.   However, I need to use a copy of the ZstdCompressor so I can keep going after some data is discarded.

**Comment by animalize** [comment]
[`ZSTD_copyCCtx()`](https://github.com/facebook/zstd/blob/v1.5.2/lib/compress/zstd_compress.c#L2281) has a limitation, it can only be used after the context is created and before [`.CONTINUE`](https://pyzstd.readthedocs.io/en/latest/#ZstdCompressor.CONTINUE) compression.
```c
/*! ZSTD_copyCCtx() :
 *  Duplicate an existing context `srcCCtx` into another one `dstCCtx`.
 *  Only works during stage ZSTDcs_init (i.e. after creation, but before first call to ZSTD_compressContinue()).
 *  pledgedSrcSize==0 means "unknown".
*   @return : 0, or an error code */
size_t ZSTD_copyCCtx(ZSTD_CCtx* dstCCtx, const ZSTD_CCtx* srcCCtx, unsigned long long pledgedSrcSize)
```

And `ZSTD_copyCCtx()` is an [experimental API](https://github.com/facebook/zstd/blob/v1.5.2/lib/zstd.h#L1067), `pyzstd` module only uses stable API, so it can be dynamically linked to zstd library. 

Maybe find some workarounds. For example, compress a frame at a time, and then discarded as a whole.

**Comment by Hello1024** [comment]
Thats a shame...

For now, for my usecase I can just waste lots of CPU and RAM and write a wrapper which can implement clone by keeping track of all method calls and replaying them to 'clone' a compressor.

I have asked in the libzstd repo if it's possible to remove this limitation anyway, since it really does seem a shortcoming for use of a compressor/decompressor to have side effects that mean it can't be put back into a previous state.

**Comment by animalize** [comment]
It feels error-prone. If the program is not written properly, the data will be ruined.

Can't compress a frame at a time? Frames are completely independent, so a frame can be discard.

**Comment by Hello1024** [comment]
Unfortunately, if the data is compressed a frame at a time, the compression rate gets far worse - since many of the messages sent have similarities there are big gains to be had by removing the inter-message redundancy.

**Comment by animalize** [comment]
If that's really a problem, maybe it's possible to write a "compression server process" with [os.fork()](https://docs.python.org/3/library/os.html#os.fork). It forks a child process, make a snapshot of the states of a compressor.

The code would be complex, and only work on Linux/macOS.
