### ISSUE TITLE
Multiprocess decompression? (#15 continuation) Corrupted block detected

### ISSUE THREAD

**Issue by codecnotsupported** [animalize/pyzstd#16]
Hi, so this a continuation of #15, I still have a (different) problem with parallelizing pyzstd, the pickle issue is resolved.
Running the same code ( see #15 ) now results in:
 ```
  File "/home/User/anaconda3/envs/test/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/User/anaconda3/envs/test/lib/python3.10/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/User/anaconda3/envs/test/lib/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
pyzstd.ZstdError: Unable to decompress zstd data: Corrupted block detected.
```
It seems like the same file descriptor is being used across multiple processes.
Am I suppose to call `pyzstd.open` for each process? (I'd have no idea how to.) 
Or is there some functionality in pyzstd I which allows for multiprocessing compatibility?
Feel free to ask for test code if you're unable to reproduce the issue.

**Comment by animalize** [comment]
`tar` format doesn't have a global header section. A `tar` file contains one or more independent files. See this page: https://jackrabbit.apache.org/oak/docs/nodestore/segment/tar.html

archive.tar.zst usually looks like this:
```
tar level: |--file1--|--file2--|--file3--|--file4--|--file5--|--file6--|--file7--|--file8--|
zst level: |---------------------------------a zstd frame----------------------------------|
```
To get the members list of a tar file ([TarFile.getmembers()](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.getmembers)), it has to iterate all files (the first decompression).
Then to get a specified file (file path from the members list), the decompression has to restart from zero (the second decompression).
And if seek to previous position, the decompression also has to restart from zero.
So, a more efficient method should be to use [TarFile.next()](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.next) method to iterate the files. (I haven't verified this yet)

> It seems like the same file descriptor is being used across multiple processes.
> Am I suppose to call pyzstd.open for each process? (I'd have no idea how to.)

After knowing the above, it is not feasible to share a zstd file descriptor among multiple processes, unless you use lock to protect `TarFile` operations.
You may iterate (read) the files in one process, and parse them in parallel (in other processes).

---------

There are other solutions, you can split the tasks, and process in parallel.

1, The semi-official [Zstandard Seekable Format](https://github.com/facebook/zstd/blob/dev/contrib/seekable_format/zstd_seekable_compression_format.md).
The zstd file has multiple frames, and there is a seek table at the end of the zstd file.
```
tar level: |--file1--|--file2--|--file3--|--file4--|--file5--|--file6--|--file7--|--file8--|
zst level: |-----zstd frame----|----------zstd frame---------|----------zstd frame---------|--seek table--|
```

2, Use zstd dictionary, see the FAQ in [this file](https://github.com/facebook/zstd/blob/dev/lib/zdict.h).
A file or a few files is a zstd frame, you also need to record the seek table in somewhere.

**Comment by codecnotsupported** [comment]
Thanks for the in-depth answer! This answers my questions.
I can personally confirm that [TarFile.next()](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.next) is faster than using [TarFile.getmembers()](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.getmembers) + [TarFile.extractfile(member)](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extractfile), as I use most contents of the archive there isn't much overhead in my case.
Closing the issue.
