### ISSUE TITLE
decompress_stream and io.TextIOWrapper don't seem to work together

### ISSUE THREAD

**Issue by moritz** [animalize/pyzstd#17]
I have a text file with 100k lines, compressed on the command line with `zstd -10 file`, and then I try to read that in python line by line:

```python
from pyzstd import decompress_stream
import io
path = 'file.zst'
with io.open(path, 'rb') as ifh:
    with io.BytesIO() as bo:
        decompress_stream(ifh, bo)
        for line in io.TextIOWrapper(bo, 'utf-8'):
            print(line)
```

This doesn't produce any output, the `for line in...` runs zero times.

Which is odd, because the `decompress_stream` example is taken straight from the docs, and `bo.getvalue()` also produces a non-empty byte string. And the `io.TextIOWrapper` works fine with an `io.BytesIO(b'a\nb\nc\n')`, so it seems that interaction between `decompress_stream` and `TextIOWrapper` is acting up.

Is this a bug, or am I just being unusually dense? :-) Or what's the recommended way to read line by line from a decompressed stream?

This is with pyzstd 0.15.3 and python 3.10.6 running on Ubuntt 22.04.1 Linux

**Comment by animalize** [comment]
[`pyzstd.open()`](https://pyzstd.readthedocs.io/en/latest/#open) supports text mode, this code should works:
```python
import pyzstd
import io
path = 'file.zst'
for line in pyzstd.open(path, 'rt', encoding='utf-8'):
    print(line)
```

**Comment by moritz** [comment]
Thank you, seems obvious in hindsight :-)
