### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by ashisa1** [animalize/pyzstd#22]
使用zstd的流式压缩来压缩网络消息，是不是不允许出现消息丢包或乱序，否则接收端解压会出错？

**Comment by animalize** [comment]
对，一个帧之中如果有损坏，损坏之后的内容很可能就丢失了。

**Comment by animalize** [comment]
如果网络通讯，可以看看文档"Frame and block"/`.FLUSH_BLOCK`。

**Comment by ashisa1** [comment]
这种错误是不时非必现的？因为我写一些简单测试用例的时候发现乱序或丢失一部分数据，还是能解压出来

**Comment by ashisa1** [comment]
> 如果网络通讯，可以看看文档"Frame and block"/`.FLUSH_BLOCK`。

独立的frame可以允许丢包或乱序，但是一个frame内的连续block不允许丢包或乱序，请问我这么理解是否正确？ 如果网络通信中存在丢包和乱序，每次使用独立帧进行压缩是否会比较影响压缩率？至少我测试zlib是这样的。不知道有没有什么更合适的方式对存在丢包乱序的通信场景进行数据压缩？

**Comment by animalize** [comment]
> 这种错误是不时非必现的？因为我写一些简单测试用例的时候发现乱序或丢失一部分数据，还是能解压出来

解压后的数据可能是错误的。
如果经常丢包、乱序，可以自己封装一个通讯协议，有hash校验，并在校验失败时重发。

**Comment by ashisa1** [comment]
我的协议本就希望支持丢包，同时我希望通过压缩降低传输带宽。我的数据都是比较小的包，如果每个包用独立的frame来压缩，能否通过traindict来提高压缩率？

**Comment by animalize** [comment]
> 我的协议本就希望支持丢包，同时我希望通过压缩降低传输带宽。

这样的话，把zstd层放在协议之上，而不是之下。

> 我的数据都是比较小的包，如果每个包用独立的frame来压缩，能否通过traindict来提高压缩率？

如果数据类型适合使用字典，会提高压缩率。

**Comment by ashisa1** [comment]
了解了，感谢~
