### ISSUE TITLE
0.15.8 is missed?

### ISSUE THREAD

**Issue by catap** [animalize/pyzstd#23]
I'm a bit confused:
 - at this repo I see 0.15.8 tag;
 - at README.md which is used as changelog I haven't see any trace of 0.15.8, instead I see 0.15.9 but haven't found any tag;
 - at PyPI I see releases up to 0.15.7.

What is the last official version of pyzstd? :)

**Comment by animalize** [comment]
v0.15.8 was released on June 13th. Today (18th) I deleted v0.15.8 from PyPI.

There was a API flaw. `write_buffer_size` argument now is renamed to `write_size`.

I saw the traffic data of `GitHub` and `readthedocs`, it's estimated that only a few dozen people have seen v0.15.8, even fewer using `write_buffer_size`.

Hope v0.15.9  can be released within this month, before that I will check if there are API flaws.

**Comment by catap** [comment]
@animalize the issue that I'm a maintainer of pyzstd at MacPorts and unfortunately I've upgraded used version to v0.15.8 a few days ago: https://github.com/macports/macports-ports/commit/7701afa137e99849cfac0b52ade43f01b9fccee8

So, technically speaking all MacPorts users may enjoy that API flaw :(

Shall I make a revert to `v0.15.7` or you may make some hotfix release soon?

Thanks.

**Comment by animalize** [comment]
Maybe few people use `write_buffer_size` argument in `ZstdFile`/`SeekableZstdFile`.
The doc has been changed to `write_size` / "added in v0.15.9", so using `write_buffer_size` is not compliant with doc.

There is a possibility that some users treat the `docstring` as a document. But I guess there will be very few people meet this situation within these days.

**Comment by animalize** [comment]
I understand your concern, users will not be able to find v0.15.8.

Please temporarily return to v0.15.7. Sorry for this accident.

**Comment by animalize** [comment]
0.15.9 released.
Close this issue.

**Comment by catap** [comment]
Thanks!
