### ISSUE TITLE
Support for wt mode in pyzstd.SeekableZstdFile

### ISSUE THREAD

**Issue by PlatonB** [animalize/pyzstd#24]
Now when trying to pass the `wt` value, an exception is raised:
```
tfo = pyzstd.SeekableZstdFile('/path/to/out.txt.zst', mode='wt')
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pbykadorov/miniconda3/lib/python3.10/site-packages/pyzstd/seekable_zstdfile.py", line 473, in __init__
    super().__init__(filename, mode,
  File "/home/pbykadorov/miniconda3/lib/python3.10/site-packages/pyzstd/zstdfile.py", line 146, in __init__
    raise ValueError("Invalid mode: {!r}".format(mode))
ValueError: Invalid mode: 'wt'
```

Is it possible to implement `mode=wt` support for creation of seekable archives?

**Comment by animalize** [comment]
`bz2.BZ2File`/`gzip.GzipFile`/`lzma.LZMAFile` classes in Python stdlib only support "binary mode". Stdlib uses `bz2.open()`/`gzip.open()`/`lzma.open()` functions to wrap the binary file object to support "text mode".

`Pyzstd` module uses the same pattern, `ZstdFile`/`SeekableZstdFile` only support "binary mode". You may write a custom `open()` function that uses `SeekableZstdFile` class, just a few lines: https://github.com/animalize/pyzstd/blob/0.15.9/src/zstdfile.py#L434-L479

**Comment by PlatonB** [comment]
```
with TextIOWrapper(SeekableZstdFile(rsmerged_jsonzst_path,
                                    mode='w',
                                    level_or_option=zstd_settings,
                                    max_frame_content_size=1024*1024)) as rsmerged_jsonzst_opened:
```
It works for me. Thanks @animalize for the tip!
P.S. Writing is extremely slow:(.

**Comment by animalize** [comment]
> P.S. Writing is extremely slow:(.

Test writing a 100 MiB `str` to `json` with this script:
```python
import json
import random
import bz2, gzip, lzma
from io import BytesIO, TextIOWrapper
from time import perf_counter

import zstandard
import pyzstd

RAW = random.randbytes(100*1024*1024).decode('latin-1')

def NO_OP(obj):
    return obj

lst = [(NO_OP, {}),
       (pyzstd.ZstdFile, {'mode':'w'}),
       (pyzstd.SeekableZstdFile, {'mode':'w',
                                  'max_frame_content_size':1024*1024}),
       (zstandard.open, {'mode':'wb'}),
       (bz2.BZ2File, {'mode':'w'}),
       (lzma.LZMAFile, {'mode':'w'}),
       (gzip.GzipFile, {'mode':'wb'}),
       ]

for callable, args in lst:
    bobj = BytesIO()
    if callable is gzip.GzipFile:
        fobj = callable(fileobj=bobj, **args)
    else:
        fobj = callable(bobj, **args)
    tobj = TextIOWrapper(fobj)

    t1 = perf_counter()
    json.dump(RAW, tobj)
    t2 = perf_counter()
    print(f'class: {callable}, time: {t2-t1:.5f}')
```
On Ubuntu 22.04, Python 3.10:
```
class: <function NO_OP at 0x7f5b2bedbd90>, time: 1.26676    # no compression
class: <class 'pyzstd.zstdfile.ZstdFile'>, time: 3.46738
class: <class 'pyzstd.seekable_zstdfile.SeekableZstdFile'>, time: 3.30347
class: <function open at 0x7f5b2ac308b0>, time: 3.47546    # zstandard module
class: <class 'bz2.BZ2File'>, time: 20.20641
class: <class 'lzma.LZMAFile'>, time: 198.26995
class: <class 'gzip.GzipFile'>, time: 309.64964
```
On Windows 10, Python 3.10:
```
class: <function NO_OP at 0x000002A29CDB3E20>, time: 1.51977    # no compression
class: <class 'pyzstd.zstdfile.ZstdFile'>, time: 4.05913
class: <class 'pyzstd.seekable_zstdfile.SeekableZstdFile'>, time: 3.91024
class: <function open at 0x000002A29D19C3A0>, time: 4.05938    # zstandard module
class: <class 'bz2.BZ2File'>, time: 20.67336
class: <class 'lzma.LZMAFile'>, time: 202.32708
class: <class 'gzip.GzipFile'>, time: 433.98347
```
It looks like the writing performance is fine.

**Comment by animalize** [comment]
The above code only uses default option for each compressor.

If the compression ratios of `zstd` and `bz2` are near, need to use a higher compression level that will greatly increase the compression time.

If the data to be compressed is text, `bz2` can be considered:
> bzip2 is particularly efficient for text data, and decompression is relatively fast.
https://en.wikipedia.org/wiki/Bzip2

**Comment by PlatonB** [comment]
@animalize It takes 10 minutes:
```
zstd /mnt/Storage/databases/dbSNP_platon/refsnp-merged.json --ultra -22 -T0
```

But that takes a whole night:
```
zstd_settings = {CParameter.compressionLevel: 22,
                 CParameter.nbWorkers: os.cpu_count() // 2}
if not os.path.exists(rsmerged_jsonzst_path):
    with bz2.open(rsmerged_jsonbz2_path,
                  mode='rt') as rsmerged_jsonbz2_opened:
        with TextIOWrapper(SeekableZstdFile(rsmerged_jsonzst_path,
                                            mode='w',
                                            level_or_option=zstd_settings,
                                            max_frame_content_size=1024*1024)) as rsmerged_jsonzst_opened:
            for rsmerged_json_line in rsmerged_jsonbz2_opened:
                rsmerged_jsonzst_opened.write(rsmerged_json_line)
```

The [source file](https://ftp.ncbi.nih.gov/snp/latest_release/JSON/refsnp-merged.json.bz2) weighs 20.4 G in unpacked form.

**Comment by animalize** [comment]
I tested this code on Ubuntu 22.04, `ZstdFile` and `zstd`'s CLI (--ultra -22 -T0) spend similar time:
```python
import io, time
import pyzstd

PATH = 'refsnp-merged.json'

zstd_option = {pyzstd.CParameter.compressionLevel:22,
               pyzstd.CParameter.nbWorkers:6}  # CPU has 6 cores

t1 = time.time()
with io.open(PATH, 'rb') as ifh:
    with pyzstd.ZstdFile(PATH + '.zst', 'w',
                         level_or_option=zstd_option) as ofh:
        while True:
            dat = ifh.read(30*1024*1024)
            if not dat:
                break
            ofh.write(dat)
t2 = time.time()
print(f'ZstdFile: {t2-t1:.4f}')
```

Maybe this iteration is inefficient? My code reads/writes 30 MiB chunks.
```python
for rsmerged_json_line in rsmerged_jsonbz2_opened:
    ...
```
In addition, when using multi-threaded compression, if only 1 MiB per frame, the speed advantage of multi-threading may not be utilized.
Each frame is too small to be split for parallel compression. Maybe only one or two threads are working.

**Comment by PlatonB** [comment]
> ```python
>     with pyzstd.ZstdFile(PATH + '.zst', 'w',
>                          level_or_option=zstd_option) as ofh:
> ```

@animalize Could you try replacing `ZstdFile` with `SeekableZstdFile` in your code? Then the compression is unlikely to be done in 30 min.

**Comment by PlatonB** [comment]
> ```python
>     with pyzstd.ZstdFile(PATH + '.zst', 'w',
>                          level_or_option=zstd_option) as ofh:
> ```

@animalize Could you try replacing `ZstdFile` with `SeekableZstdFile` in your code? Then the compression is unlikely to be done in 30 min.

**Comment by animalize** [comment]
> Then the compression is unlikely to be done in 30 min.

This is expected, as mentioned in the last paragraph "In addition, ...".
 
It's possible to write a subclass of `SeekableZstdFile` that uses Python to spawn threads for parallel compression (a thread compresses a frame), rather than using zstd library to spawn threads.

**Comment by PlatonB** [comment]
@animalize Yes, this script is very fast:
```
MTSeekableZstdFile 320.2485
```

P.S. I published an MVP of `SeekableZstdFile`-based [indexer for huge tables](https://github.com/PlatonB/antidb). Currently the default compression level there is 6. In bioinformatics, many tables weigh tens of GB, which quickly fills up space on a work computer. It would be ideal to have the ability to compress them at maximum level in a tolerable amount of time.

**Comment by animalize** [comment]
> this script is very fast:
> MTSeekableZstdFile 320.2485

It looks good, I was worried that GIL would affect performance. 

This is an improved version. Mainly to prevent RAM exhausted when writing throughput is the bottleneck, and some robustness improvements. The class/argument names changed.
https://github.com/animalize/pyzstd_extension/blob/main/pyzstd_extension.py

If your data is structured, consider using zstd dictionary, which may improve the compression ratio a bit.
https://github.com/facebook/zstd/issues/3603#issuecomment-1505480744

**Comment by PlatonB** [comment]
Will this code or some ideas from there become part of pyzstd?

**Comment by animalize** [comment]
It will not be a part of `pyzstd`, but I will add a link to the doc.

It can also add a `SeekableZstdFile` subclass that verify `XXH64` checksums, and a `ZstdTarFile` subclass that generate one frame for each file.

The API doesn't guarantee stability.
