### ISSUE TITLE
Wheel for python 3.10

### ISSUE THREAD

**Issue by miurahr** [animalize/pyzstd#8]
CPython 3.10 is released last week.
Downstream projects wait a wheel for python 3.10.

**Comment by animalize** [comment]
I pushed a commit to `release` branch on 2 Sep, in the rc stage of 3.10.
https://github.com/animalize/pyzstd/commit/0e3283e9a4d6ec8442a2759c584f4ec2962b1a83

So the PyPi page already has 3.10 wheels
https://pypi.org/project/pyzstd/#files

And then merge the commit to `dev` branch:
https://github.com/animalize/pyzstd/commit/187b8ca6ea0f6f819f6de7fbe35d4e5719996f68

I estimate `zstd` v1.5.1 will be released within one month, and then `pyzstd` 0.15.1 will be released.

**Comment by miurahr** [comment]
Oh, thank you.
