### ISSUE TITLE
多线程版本，预计什么时候能上呀？

### ISSUE THREAD

**Issue by calllivecn** [animalize/pyzstd#9]

**Comment by animalize** [comment]
一直就支持多线程啊。

**Comment by calllivecn** [comment]
In [68]: pyzstd.zstd_version                                                                                                   │
Out[68]: '1.5.0'

**Comment by calllivecn** [comment]
In [68]: pyzstd.zstd_version
Out[68]: '1.5.0'

**Comment by calllivecn** [comment]
In [68]: pyzstd.zstd_version
Out[68]: '1.5.0'
In [70]: print(pyzstd.zstd_support_multithread)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-70-c0231ff05ba3> in <module>
----> 1 print(pyzstd.zstd_support_multithread)

AttributeError: module 'pyzstd' has no attribute 'zstd_support_multithread'


0.15.0 是默认开启的吗？我之前测试时，看是单核的。

**Comment by animalize** [comment]
`pyzstd.zstd_support_multithread`是0.15.1添加的，这个版本还没发布。
可以假设支持多线程，只有动态链接到系统提供的zstd库时才有可能不支持多线程，绝大多数人不会遇到这种情况。

**Comment by calllivecn** [comment]
嗯？没怎么明白。
那0.15.0 是支持多线程还是不支持？

我的环境：
ubuntu21.10

有安装zstd：
```shell
$ dpkg -l |grep -i zstd
ii  libzstd1:amd64                                   1.4.8+dfsg-2.1                      amd64        fast lossless compression algorithm
ii  zstd                                             1.4.8+dfsg-2.1                      amd64        fast lossless compression algorithm -- CLI tool
```

直接 pip 安装的，好像没看到有本地编译过程。

**Comment by animalize** [comment]
> 那0.15.0 是支持多线程还是不支持？

从PyPI或Anaconda安装的都支持。
只有自己编译pzystd模块、并且动态链接到系统zstd库的，**才有可能**不支持。
我改一下文档，省得在这个问题浪费精力。

**Comment by animalize** [comment]
pyzstd自带了zstd库源码，默认是静态链接的。

**Comment by calllivecn** [comment]
> > 那0.15.0 是支持多线程还是不支持？
> 
> 从PyPI或Anaconda安装的都支持。 只有自己编译pzystd模块、并且动态链接到系统zstd库的，**才有可能**不支持。 我改一下文档，省得在这个问题浪费精力。

是1.5.0哈前面写错。

从你刚才的回答，我解理的是1.5.0目前是支持多线程压缩的。
但我刚刚测试的是单核的：
```python
import ssl
import pyzstd

zstd = pyzstd.ZstdCompressor()
while True:
    data = ssl.RAND_bytes((1<<20))
    zstd.compress(data)
```
通过pip 安装的：

```shell
$ unzip -l pyzstd-0.15.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl 
Archive:  pyzstd-0.15.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
        7  2021-09-02 03:29   pyzstd-0.15.0.dist-info/top_level.txt
      148  2021-09-02 03:29   pyzstd-0.15.0.dist-info/WHEEL
     1522  2021-09-02 03:29   pyzstd-0.15.0.dist-info/LICENSE
     3836  2021-09-02 03:29   pyzstd-0.15.0.dist-info/METADATA
      800  2021-09-02 03:29   pyzstd-0.15.0.dist-info/RECORD
     6400  2021-09-02 03:25   pyzstd/__init__.pyi
    20599  2021-09-02 03:25   pyzstd/__init__.py
        0  2021-09-02 03:25   pyzstd/py.typed
     4103  2021-09-02 03:25   pyzstd/c/c_pyzstd.py
 12665136  2021-09-02 03:26   pyzstd/c/_zstd.cpython-39-x86_64-linux-gnu.so
---------                     -------
 12702551                     10 files
```
这里看包内容，应该是使用的自带的so.

**Comment by animalize** [comment]
` 12665136  2021-09-02 03:26   pyzstd/c/_zstd.cpython-39-x86_64-linux-gnu.so`
这就是pyzstd的.so，包括“自带的zstd库”和“用C写的Python封装”。

动态链接几乎没人用，除了数据中心之类的有特殊需求的地方。

**Comment by calllivecn** [comment]
如果是支持多线程压缩的，像我上面的测试代码，不应该是能把所有核心都利用起来的吗？

可我刚刚实测的，它只利用了一个核压缩呀？

是我的使用姿势不对吗？

**Comment by animalize** [comment]
要指定线程数，比如：
```python
        option = {CParameter.compressionLevel : 5,
                        CParameter.nbWorkers : 8}  # 使用8线程压缩
        compressed_dat = compress(dat, option)
```

**Comment by calllivecn** [comment]
感谢～可以了。

**Comment by animalize** [comment]
不客气。
